var items = {
    entradas: [
        { _name: "Bolo do Caco",
            _price: 250,
            _desc: "Pão tradicional da Madeira, servido com manteiga de alho.",
            _img: "sagriao.jpg",
            _classif: 4,
            _ctime: 2,
            _ingredients: ["Manteiga de Alho"] },

        { _name: "Caldo Verde",
            _price: 300,
            _desc: "Tradicional caldo português à base de couve.",
            _img: "caldoverde.jpg",
            _classif: 5,
            _ctime: 2,
            _ingredients: ["Couve", "Pessoas mortas", "Ovo"] },

        { _name: "Sopa de Castanha",
            _price: 250,
            _desc: "Tradicional da Grandiosa Ilha da Madeira.",
            _img: "scastanha.jpg",
            _classif: 4,
            _ctime: 2,
            _ingredients: ["Castanha"] },
    ],
    sopas: [
        { _name: "Sopa de Agrião",
            _price: 250,
            _desc: "Com o agrião mais fresco da nossa região.",
            _img: "sagriao.jpg",
            _classif: 4,
            _ctime: 2,
            _ingredients: ["Agrião", "Cenoura"] },

        { _name: "Caldo Verde",
            _price: 300,
            _desc: "Tradicional caldo português à base de couve.",
            _img: "caldoverde.jpg",
            _classif: 5,
            _ctime: 2,
            _ingredients: ["Couve", "Pessoas mortas", "Ovo"] },

        { _name: "Sopa de Castanha",
            _price: 250,
            _desc: "Tradicional da Grandiosa Ilha da Madeira.",
            _img: "scastanha.jpg",
            _classif: 4,
            _ctime: 2,
            _ingredients: ["Castanha"] },
    ],
    pratos: [
        { _name: "Bitoque",
            _price: 600,
            _desc: "Batata frita com arroz acompanhada com carne de porco.",
            _img: "bitoque.jpg",
            _classif: 3,
            _ctime: 5,
            _ingredients: ["Arroz", "Salada", "Ovo"] },

        { _name: "Espetada",
            _price: 720,
            _desc: "Carne de vaca num pau de louro.",
            _img: "espetada.jpg",
            _classif: 4,
            _ctime: 10,
            _ingredients: ["Arroz", "Salada", "Ovo"] },

        { _name: "Picado de Carne",
            _price: 650,
            _desc: "Batata frita com arroz acompanhada com pedaços de carne de vaca.",
            _img: "picado.jpg",
            _classif: 5,
            _ctime: 8,
            _ingredients: ["Batata", "Arroz", "Salada"] },
    ]
};
