var items = {
    entradas: [
        { _name: "Bolo do Caco",
            _price: 250,
            _desc: "Pão tradicional da Madeira, servido com manteiga de alho.",
            _img: "bolocaco.jpg",
            _classif: 4,
            _ctime: 2,
            _ingredients: ["Manteiga de Alho"] },

        { _name: "Camarões",
            _price: 400,
            _desc: "Prato de camarões temperados e molho cocktail.",
            _img: "camaroes.jpg",
            _classif: 5,
            _ctime: 1,
            _ingredients: ["Molho cocktail"] },
    ],
    sopas: [
        { _name: "Sopa de Agrião",
            _price: 250,
            _desc: "Com o agrião mais fresco da nossa região.",
            _img: "sagriao.jpg",
            _classif: 4,
            _ctime: 3,
            _ingredients: ["Agrião", "Cenoura"] },

        { _name: "Caldo Verde",
            _price: 300,
            _desc: "Tradicional caldo português à base de couve.",
            _img: "caldoverde.jpg",
            _classif: 5,
            _ctime: 3,
            _ingredients: [ "Choriço", "Alho"] },

        { _name: "Sopa de Castanha",
            _price: 250,
            _desc: "Tradicional da Grandiosa Ilha da Madeira.",
            _img: "scastanha.jpg",
            _classif: 4,
            _ctime: 3,
            _ingredients: ["Cebola", "Alho"] },
    ],
    pratos: [
        { _name: "Bitoque de Porco",
            _price: 600,
            _desc: "Bitoque à portuguesa, com um ovo a cavalo.",
            _img: "bitoque.jpg",
            _classif: 5,
            _ctime: 5,
            _ingredients: ["Arroz", "Salada", "Ovo", "Batatas fritas"] },

        { _name: "Espetada",
            _price: 720,
            _desc: "Carne de vaca em pau de louro.",
            _img: "espetada.jpg",
            _classif: 4,
            _ctime: 10,
            _ingredients: ["Arroz", "Salada", "Milho frito"] },

        { _name: "Picado de Carne",
            _price: 650,
            _desc: "Pedaços de carne de vaca, fritos, com molho de natas.",
            _img: "picado.jpg",
            _classif: 5,
            _ctime: 8,
            _ingredients: ["Batata", "Arroz", "Salada", "Molho de natas"] },
    ],
    bebidas: [
        { _name: "Cerveja Coral",
            _price: 125,
            _desc: "Gasolina da Madeira.",
            _img: "cerveja.jpg",
            _classif: 2,
            _ctime: 1,
            _ingredients: [] },

        { _name: "Coca-Cola",
            _price: 150,
            _desc: "O clássico refrigerante que te vai dar diabetes daqui a uns anos.",
            _img: "cocacola.jpg",
            _classif: 4,
            _ctime: 1,
            _ingredients: [] },

        { _name: "Brisa-Maçã",
            _price: 150,
            _desc: "Refrigerante de maçã tradicional da Madeira.",
            _img: "brisa.jpg",
            _classif: 3,
            _ctime: 8,
            _ingredients: [] },
    ],
    sobremesas: [
        { _name: "Broas de Mel",
            _price: 250,
            _desc: "Broas tradicionais portuguesas, com canela, que a tua avó te dá no 'pão por Deus'.",
            _img: "broas.jpg",
            _classif: 5,
            _ctime: 1,
            _ingredients: [] },

        { _name: "Arroz Doce",
            _price: 300,
            _desc: "O clássico português com canela.",
            _img: "arrozdoce.jpg",
            _classif: 4,
            _ctime: 1,
            _ingredients: [] },

        { _name: "Serradura",
            _price: 300,
            _desc: "Doce de bolacha com natas e leite condensado.",
            _img: "serradura.jpg",
            _classif: 4,
            _ctime: 1,
            _ingredients: [] },
    ],
    cafetaria: [
        { _name: "Carioca de Limão",
            _price: 100,
            _desc: "Infusão preparada com casca de limão.",
            _img: "carioca.jpg",
            _classif: 3,
            _ctime: 1,
            _ingredients: [] },

        { _name: "Café",
            _price: 100,
            _desc: "É café.",
            _img: "cafe.jpg",
            _classif: 4,
            _ctime: 1,
            _ingredients: [] },

        { _name: "Galão",
            _price: 80,
            _desc: "Deliciosa bebida de café e leite.",
            _img: "galao.jpg",
            _classif: 5,
            _ctime: 1,
            _ingredients: [] },
    ]
};
